//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class ALE_ALERTA_LISTA_PERSONA : Entity<long>
    {
        public long ID_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public System.DateTime FECHA_ALERTA { get; set; }
    }
}
