//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALE_TIPO_ALERTA: Entity<int>
    {
        public ALE_TIPO_ALERTA()
        {
            this.ALE_ALERTA = new HashSet<ALE_ALERTA>();
            this.ALE_NOTIFICACION_ALERTA = new HashSet<ALE_NOTIFICACION_ALERTA>();
            this.ALE_OPERACION_IRREGULAR = new HashSet<ALE_OPERACION_IRREGULAR>();
        }

    
        public string DESCRIPCION { get; set; }
        public bool NOTIFICAR { get; set; }
        public bool REPORTE { get; set; }
        public string COLOR { get; set; }


        public virtual ICollection<ALE_ALERTA> ALE_ALERTA { get; set; }
        public virtual ICollection<ALE_NOTIFICACION_ALERTA> ALE_NOTIFICACION_ALERTA { get; set; }
        public virtual ICollection<ALE_OPERACION_IRREGULAR> ALE_OPERACION_IRREGULAR { get; set; }
    }
}