//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALE_OPERACION_IRREGULAR : Entity<int>
    {
        public int ID_AGENCIA { get; set; }
        public int ID_TIPO_ALERTA { get; set; }
        public string EXPRESION { get; set; }
        public string DESCRIPCION { get; set; }

        public virtual ALE_TIPO_ALERTA ALE_TIPO_ALERTA { get; set; }
        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
    }
}
