//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class ALE_BLOQUEO_PRESTAMO : Entity<int>
    {
        public string SECUENCIA { get; set; }
        public string PRESTAMO { get; set; }
        public string ESTADO { get; set; }
    }
}
