//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALE_ALERTA: Entity<long>
    {
        /// <summary>
        /// CONSTANTES PARA EL MANEJO DEL FLUJO DE ALERTAS
        /// </summary>
        public static string ESTADO_NATIFICADA = "NOTIFICADA";
        public static string ESTADO_ANALIZADA = "ANALIZADA";
        public static string ESTADO_PROCESADAA = "PROCESADA-ACEPTADA";
        public static string ESTADO_PROCESADAR = "PROCESADA-RECHAZADA";
        public static string ESTADO_DESCARTADA = "DESCARTADA";


        public int ID_AGENCIA { get; set; }
        public int ID_TIPO_ALERTA { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public System.DateTime FECHA_MOVIMIENTO { get; set; }
        public decimal VALOR_PAGO { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_ALERTA { get; set; }
        public string COLOR { get; set; }
        public string DESCRIPCION_ALERTA { get; set; }
        public string ESTADO_ANTERIOR { get; set; }
        public string ESTADO_ACTUAL { get; set; }
        public string PRESTAMO { get; set; }
        public string SECUENCIA { get; set; }
        public string CLASE_PRODUCTO { get; set; }
        public string BANCO_TRANSACCION { get; set; }
        public string CODIGO_AGENCIA { get; set; }
        public string ANALISIS_CASO { get; set; }
        public string CODIGO_EJECUTIVO { get; set; }

        public virtual ALE_TIPO_ALERTA ALE_TIPO_ALERTA { get; set; }
        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
    }
}