//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALE_CONTACTO_ALERTA: Entity<int>
    {
         public ALE_CONTACTO_ALERTA()
        {
            this.ALE_NOTIFICACION_ALERTA = new HashSet<ALE_NOTIFICACION_ALERTA>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<ALE_NOTIFICACION_ALERTA> ALE_NOTIFICACION_ALERTA { get; set; }
    }
}
