//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_ROS: Entity<long>
    {
        public MON_ROS()
        {
            this.MON_ROS_ARCHIVOS = new HashSet<MON_ROS_ARCHIVOS>();
            this.MON_ROS_OPERACION = new HashSet<MON_ROS_OPERACION>();
            this.MON_ROS_ACTOR = new HashSet<MON_ROS_ACTOR>();
        }
    
        public string CODIGO_UIF { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public string DESCRIPCION_OPERACION_REPORTADA { get; set; }
        public string ANALISIS_CASO { get; set; }
    
        public virtual ICollection<MON_ROS_ARCHIVOS> MON_ROS_ARCHIVOS { get; set; }
        public virtual ICollection<MON_ROS_OPERACION> MON_ROS_OPERACION { get; set; }
        public virtual ICollection<MON_ROS_ACTOR> MON_ROS_ACTOR { get; set; }
    }
}
