//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_ROS_OPERACION: Entity<long>
    {
        

        public long ID_ROS { get; set; }
        public string ID_TRANSACCION { get; set; }
        public int ID_AGENCIA_BANCO { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public long NUMERO_PRESTAMO { get; set; }
        public decimal VALOR_PAGADO { get; set; }
        public int ID_PAIS { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_MUNICIPIO { get; set; }
        public string DIRECCION_FINANCIERA { get; set; }
        public string PROCEDENCIA_DESTINO { get; set; }
        public string RAZON_ROS { get; set; }
        public Nullable<long> ID_TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string ID_TIPO_PRODUCTO { get; set; }
    
        public virtual MON_AGENCIA_BANCARIA MON_AGENCIA_BANCARIA { get; set; }
        public virtual MON_ROS MON_ROS { get; set; }
        public string AGENCIABANCO { get; set; }
        public string BANCO { get; set; }
    }
}
