//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_CAT_FINANCIERA:Entity<int>
    {
        public MON_CAT_FINANCIERA()
        {
            this.MON_AGENCIA_BANCARIA = new HashSet<MON_AGENCIA_BANCARIA>();
        }

        public int CODIGO_FINANCIERA { get; set; }
        public string DESCRIPCION { get; set; }


        public virtual ICollection<MON_AGENCIA_BANCARIA> MON_AGENCIA_BANCARIA { get; set; }
    }
}
