//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MON_ROS_ACTOR : Entity<long>
    {
        public long ID_ROS { get; set; }
        public string RELACION_CON_SO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string APELLIDO_CASADA { get; set; }
        public string TIPO_PERSONA { get; set; }
        public string GENERO { get; set; }
        public string ID_ESTADO_FAMILIAR { get; set; }
        public Nullable<int> ID_ACTIVIDAD_ECONOMICA { get; set; }
        public Nullable<int> ID_NACIONALIDAD { get; set; }
        public Nullable<int> ID_PAIS { get; set; }
        public Nullable<int> ID_DEPARTAMENTO { get; set; }
        public Nullable<int> ID_MUNICIPIO { get; set; }
        public Nullable<int> ID_URBANIZACION { get; set; }
        public Nullable<int> ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> ID_PROFESION { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string DIRECCION_ESPECIFICA { get; set; }

        public virtual MON_ROS MON_ROS { get; set; }
        public string CIVIL { get; set; }
        public string ECONOMICA { get; set; }
        public string NACIONALIDAD { get; set; }
        public string PAIS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string URBANIZACION { get; set; }
        public string TDOCUMENTO { get; set; }
        public string PROFESION { get; set; }
    }
}
