//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_OFICIO_PERSONA: Entity<long>
    {
        public string INSTITUCIONES;

        public long ID_OFICIO { get; set; }
        public string NOMBRE { get; set; }
        public string GENERALES { get; set; }
        public string DUI { get; set; }
        public string NIT { get; set; }
        public Nullable<long> TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string TIPO_PERSONA { get; set; }
        public string RESULTADO { get; set; }
        public bool COTIZACIONES { get; set; }
        public bool SOLICITUDES { get; set; }
        public bool PRESTAMOS { get; set; }
        public bool CHEQUES { get; set; }
        public bool AEX { get; set; }

        public virtual MON_OFICIO MON_OFICIO { get; set; }

        public string NUMERO_OFICIO { get; set; }
    }
}
