//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_CAT_INSTITUCION:Entity<int>
    {
        public MON_CAT_INSTITUCION()
        {
            this.MON_CARGO_INSTITUCION = new HashSet<MON_CARGO_INSTITUCION>();
            this.MON_CAT_UNIDAD = new HashSet<MON_CAT_UNIDAD>();
        }

        public string NOMBRE { get; set; }

        public virtual ICollection<MON_CARGO_INSTITUCION> MON_CARGO_INSTITUCION { get; set; }
        public virtual ICollection<MON_CAT_UNIDAD> MON_CAT_UNIDAD { get; set; }
    }
}
