//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_CONTACTO_INSTITUCION:Entity<int>
    {
        public MON_CONTACTO_INSTITUCION()
        {
            this.MON_OFICIO = new HashSet<MON_OFICIO>();
            this.MON_OFICIO1 = new HashSet<MON_OFICIO>();
            this.MON_OFICIO2 = new HashSet<MON_OFICIO>();
        }

        public int ID_UNIDAD { get; set; }
        public int ID_CARGO_INSTITUCION { get; set; }
        public int ID_TITULO { get; set; }
        public string NOMBRE { get; set; }

        public virtual LIS_CAT_TITULOS LIS_CAT_TITULOS { get; set; }
        public virtual MON_CARGO_INSTITUCION MON_CARGO_INSTITUCION { get; set; }
        public virtual MON_CAT_UNIDAD MON_CAT_UNIDAD { get; set; }
        public virtual ICollection<MON_OFICIO> MON_OFICIO { get; set; }
        public virtual ICollection<MON_OFICIO> MON_OFICIO1 { get; set; }
        public virtual ICollection<MON_OFICIO> MON_OFICIO2 { get; set; }
    }
}
