//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_OFICIO_CONFIGURACION: Entity<long>
    {
        public int ID_INSTITUCION { get; set; }
        public int ID_CONTACTO_INSTITUCION_OFICIAL { get; set; }
        public int DIAS_NOTIFICACION { get; set; }
    }
}
