//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_SDN_DIRECCION : Entity<int>
    {
        public int ID_LIS_SDN { get; set; }
        public string DIRECCION { get; set; }
        public string ESTADO_PROVINCIA { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }

        public virtual LIS_SDN LIS_SDN { get; set; }
    }
}
