//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_CAT_GRUPO_FATF : Entity<int>
    {
        public LIS_CAT_GRUPO_FATF()
        {
            this.LIS_PAIS_GRUPO = new HashSet<LIS_PAIS_GRUPO>();
        }
    

        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string WEB { get; set; }
    
        public virtual ICollection<LIS_PAIS_GRUPO> LIS_PAIS_GRUPO { get; set; }
    }
}
