//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PEP_RELACION : Entity<int>
    {
        public int ID_LIS_PEP { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string GRADO_PARENTESCO { get; set; }
        public string DESCRIPCION_RELACION { get; set; }

        public virtual LIS_PEP LIS_PEP { get; set; }
    }
}
