//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PEP_CARGO : Entity<int>
    {
        public int ID_LIS_PEP { get; set; }
        public int ID_ORGANO { get; set; }
        public int ID_ENTIDAD { get; set; }
        public string NOMBRE_CARGO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }

        public virtual LIS_CAT_ENTIDADES LIS_CAT_ENTIDADES { get; set; }
        public virtual LIS_CAT_ORGANOS LIS_CAT_ORGANOS { get; set; }
        public virtual LIS_PEP LIS_PEP { get; set; }
    }
}
