//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_SDN : Entity<int>
    {
        public LIS_SDN()
        {
            this.LIS_SDN_AKA = new HashSet<LIS_SDN_AKA>();
            this.LIS_SDN_DIRECCION = new HashSet<LIS_SDN_DIRECCION>();
            this.LIS_SDN_DOCUMENTO = new HashSet<LIS_SDN_DOCUMENTO>();
            this.LIS_SDN_NACIONALIDAD = new HashSet<LIS_SDN_NACIONALIDAD>();
        }

        public int UID { get; set; }
        public string TIPO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string PROGRAMAS { get; set; }

        public virtual ICollection<LIS_SDN_AKA> LIS_SDN_AKA { get; set; }
        public virtual ICollection<LIS_SDN_DIRECCION> LIS_SDN_DIRECCION { get; set; }
        public virtual ICollection<LIS_SDN_DOCUMENTO> LIS_SDN_DOCUMENTO { get; set; }
        public virtual ICollection<LIS_SDN_NACIONALIDAD> LIS_SDN_NACIONALIDAD { get; set; }
    }
}
