//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PERSONALIZADA_ALIAS : Entity<int>
    {
        public int ID_LISTA_PERSONALIZADA { get; set; }
        public string ALIAS { get; set; }
        public string CALIDAD { get; set; }
        public string COMENTARIO { get; set; }

        public virtual LIS_PERSONALIZADA LIS_PERSONALIZADA { get; set; }
    }
}
