//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_ONU_ALIAS : Entity<int>
    {
        public int ID_LIS_ONU { get; set; }
        public string QUALITY { get; set; }
        public string ALIAS_NAME { get; set; }
        public string CITY_OF_BIRTH { get; set; }
        public string COUNTRY_OF_BIRTH { get; set; }
        public string NOTE { get; set; }

        public virtual LIS_ONU LIS_ONU { get; set; }
    }
}
