//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_GENERAL : Entity<int>
    {
        public LIS_GENERAL()
        {
            this.LIS_GENERAL_PERSONALIZADA = new HashSet<LIS_GENERAL_PERSONALIZADA>();
        }
        
        public string NOMBRE_LISTA { get; set; }
        public string DESCRIPCION_LISTA { get; set; }
        public string URL_LISTA { get; set; }
        public Nullable<bool> LLENADO_AUTOMATICO { get; set; }        

        public virtual ICollection<LIS_GENERAL_PERSONALIZADA> LIS_GENERAL_PERSONALIZADA { get; set; }
    }
}
