//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PERSONALIZADA : Entity<int>
    {
        public LIS_PERSONALIZADA()
        {
            this.LIS_GENERAL_PERSONALIZADA = new HashSet<LIS_GENERAL_PERSONALIZADA>();
            this.LIS_PERSONALIZADA_ALIAS = new HashSet<LIS_PERSONALIZADA_ALIAS>();
            this.LIS_PERSONALIZADA_DIRECCION = new HashSet<LIS_PERSONALIZADA_DIRECCION>();
            this.LIS_PERSONALIZADA_DOCUMENTO = new HashSet<LIS_PERSONALIZADA_DOCUMENTO>();
        }

        public string ID_UNICO { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string TERCER_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string TERCER_APELLIDO { get; set; }
        public Nullable<int> PAIS_NACIMIENTO { get; set; }
        public string RAZON { get; set; }

        public virtual ICollection<LIS_GENERAL_PERSONALIZADA> LIS_GENERAL_PERSONALIZADA { get; set; }
        public virtual ICollection<LIS_PERSONALIZADA_ALIAS> LIS_PERSONALIZADA_ALIAS { get; set; }
        public virtual ICollection<LIS_PERSONALIZADA_DIRECCION> LIS_PERSONALIZADA_DIRECCION { get; set; }
        public virtual ICollection<LIS_PERSONALIZADA_DOCUMENTO> LIS_PERSONALIZADA_DOCUMENTO { get; set; }
        public string PAIS_NACIMIENTO_NOMBRE { get; set; }
    }
}
