//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PERSONALIZADA_DIRECCION : Entity<int>
    {
        public int ID_LISTA_PERSONALIZADA { get; set; }
        public string DIRECCION_ESPECIFICA { get; set; }
        public string AVENIDA_CALLE_PASAJE { get; set; }
        public Nullable<int> ID_URBANIZACION { get; set; }
        public Nullable<int> ID_MUNICIPIO { get; set; }
        public Nullable<int> ID_DEPARTAMENTO { get; set; }
        public Nullable<int> ID_PAIS { get; set; }
        public string COMENTARIO { get; set; }

        public virtual LIS_PERSONALIZADA LIS_PERSONALIZADA { get; set; }
        public string URBANIZACION { get; set; }
        public string MUNICIPIO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PAIS { get; set; }
    }
}
