//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PAIS_GRUPO : Entity<int>
    {

        public int ID_GRUPO { get; set; }
        public int ID_PAIS { get; set; }
        public string MOTIVO_INGRESO { get; set; }
    
        public virtual LIS_CAT_GRUPO_FATF LIS_CAT_GRUPO_FATF { get; set; }
    }
}
