//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_EXENTO : Entity<int>
    {
        public long CODIGO_CLIENTE { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string NUMERO_IDENTIFICACION_2 { get; set; }
        public string NOMBRES { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string APELLIDO_DE_CASADA { get; set; }
        public string PAIS_NACIMIENTO { get; set; }
        public string COMENTARIO { get; set; }
        public string MOTIVO_INGRESO { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA { get; set; }
    }
}
