//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_ONU : Entity<int>
    {
        public LIS_ONU()
        {
            this.LIS_ONU_ALIAS = new HashSet<LIS_ONU_ALIAS>();
            this.LIS_ONU_DIRECCION = new HashSet<LIS_ONU_DIRECCION>();
            this.LIS_ONU_DOCUMENTO = new HashSet<LIS_ONU_DOCUMENTO>();
        }
        public int DATA_ID { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> VERSION_NUM { get; set; }
        public string FIRST_NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string THIRD_NAME { get; set; }
        public string FOURTH_NAME { get; set; }
        public string UN_LIST_TYPE { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public Nullable<System.DateTime> LISTED_ON { get; set; }
        public string COMMENTS { get; set; }
        public string NATIONALITY { get; set; }

        public virtual ICollection<LIS_ONU_ALIAS> LIS_ONU_ALIAS { get; set; }
        public virtual ICollection<LIS_ONU_DIRECCION> LIS_ONU_DIRECCION { get; set; }
        public virtual ICollection<LIS_ONU_DOCUMENTO> LIS_ONU_DOCUMENTO { get; set; }
    }
}
