//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_CAT_TITULOS : Entity<int>
    {
        public LIS_CAT_TITULOS()
        {
            this.LIS_PEP = new HashSet<LIS_PEP>();
            this.MON_CONTACTO_INSTITUCION = new HashSet<MON_CONTACTO_INSTITUCION>();
        }

        public string ABREVIATURA { get; set; }
        public string DESCRIPCION { get; set; }

        public virtual ICollection<LIS_PEP> LIS_PEP { get; set; }
        public virtual ICollection<MON_CONTACTO_INSTITUCION> MON_CONTACTO_INSTITUCION { get; set; }
    }
}
