//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_CAT_ORGANOS : Entity<int>
    {
        public LIS_CAT_ORGANOS()
        {
            this.LIS_CAT_ENTIDADES = new HashSet<LIS_CAT_ENTIDADES>();
            this.LIS_PEP_CARGO = new HashSet<LIS_PEP_CARGO>();
        }
    

        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<LIS_CAT_ENTIDADES> LIS_CAT_ENTIDADES { get; set; }
        public virtual ICollection<LIS_PEP_CARGO> LIS_PEP_CARGO { get; set; }
    }
}
