//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class LIS_PEP : Entity<int>
    {
        public LIS_PEP()
        {
            this.LIS_PEP_CARGO = new HashSet<LIS_PEP_CARGO>();
            this.LIS_PEP_RELACION = new HashSet<LIS_PEP_RELACION>();
        }

        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string APELLIDO_CASADA { get; set; }
        public string CONOCIDO_POR { get; set; }
        public string DUI { get; set; }
        public string NIT { get; set; }
        public string PASAPORTE { get; set; }
        public string CARNET_RESIDENTE { get; set; }
        public string FUNCIONARIO_O_RELACION { get; set; }
        public Nullable<bool> DECLARACION_JURADA { get; set; }
        public Nullable<int> TITULO_CARGO_PEP { get; set; }

        public virtual LIS_CAT_TITULOS LIS_CAT_TITULOS { get; set; }
        public virtual ICollection<LIS_PEP_CARGO> LIS_PEP_CARGO { get; set; }
        public virtual ICollection<LIS_PEP_RELACION> LIS_PEP_RELACION { get; set; }
        public string ABREVIATURA_TITULO { get; set; }
        public string TITULO { get; set; }
    }
}