//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    
    public partial class SEG_LOG_AUDITORIA
    {
        [Key, Column(Order = 0)]
        [DataMember]
        public long ID { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public long ID_ORIGEN { get; set; }
        public string ACCION { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string VALOR_ANTERIOR { get; set; }
        public string VALOR_ACTUAL { get; set; }
        public string USUARIO { get; set; }
    }
}
