//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_CARGAR_DATOS: Entity<long>
    {
        /// <summary>
        /// CONSTANTES PARA EL MANEJO DE ESTADOS
        /// </summary>
        public static string ESTADO_ENPROCESO = "EN PROCESO";
        public static string ESTADO_ERROR= "ERROR";
        public static string ESTADO_LISTO = "LISTO";

        /// <summary>
        /// CONSTANTES DE ID TABLAS QUE USAN LA CARGA DE DATOS
        /// </summary>
        public static long ID_SDN = 1;
        public static long ID_ONU = 2;


        public string NOMBRE_TABLA { get; set; }
        public int TOTAL_REGISTROS { get; set; }
        public string ESTADO { get; set; }
        public string MENSAJE { get; set; }
    }
}
