//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class SEG_PERMISO : Entity<int>
    {
        public static string EDITAR = "EDITAR";
        public static string AGREGAR = "AGREGAR";
        public static string ELIMINAR = "ELIMINAR";
        public static string GREPORTES = "GREPORTES";
        public static string APRIVILEGIOS = "APRIVILEGIOS";
        public static string GMATRIZ = "GMATRIZ";
        public static string POFICIOS = "POFICIOS";
        public static string PALERTA = "PALERTA";
        public static string AALERTA = "AALERTA";
        public static string DALERTA = "DALERTA";
        public static string ALISTAS ="ALISTAS";
        public static string ACONFGOFICIO = "ACONFGOFICIO";
        public static string ACONFGFACTORES = "ACONFGFACTORES";
        public static string DESCARGAR = "DESCARGAR";

        public SEG_PERMISO()
        {
            this.SEG_ROL_PERMISO = new HashSet<SEG_ROL_PERMISO>();
        }


        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }

        public virtual ICollection<SEG_ROL_PERMISO> SEG_ROL_PERMISO { get; set; }
    }
}
