//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class SEG_MODULO : Entity<int>
    {
        public SEG_MODULO()
        {
            this.SEG_ACCESO_USUARIO = new HashSet<SEG_ACCESO_USUARIO>();
            this.SEG_OPCION = new HashSet<SEG_OPCION>();
        }

  
        public string DESCRIPCION { get; set; }

        public virtual ICollection<SEG_ACCESO_USUARIO> SEG_ACCESO_USUARIO { get; set; }
        public virtual ICollection<SEG_OPCION> SEG_OPCION { get; set; }
    }
}
