//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class SEG_ROL : Entity<int>
    {
        public SEG_ROL()
        {
            this.SEG_ACCESO_USUARIO = new HashSet<SEG_ACCESO_USUARIO>();
            this.SEG_ROL_USUARIO = new HashSet<SEG_ROL_USUARIO>();
            this.SEG_ROL_PERMISO = new HashSet<SEG_ROL_PERMISO>();
        }

        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public bool ALERTA_NOTIFICADA { get; set; }
        public bool ALERTA_ANALIZADA { get; set; }
        public bool ALERTA_OFICIO { get; set; }
        public bool ALERTA_PERSONA_LISTA { get; set; }
        public bool ALERTA_PERFIL_TRANSACCIONAL { get; set; }


        public virtual ICollection<SEG_ACCESO_USUARIO> SEG_ACCESO_USUARIO { get; set; }
        public virtual ICollection<SEG_ROL_USUARIO> SEG_ROL_USUARIO { get; set; }
        public virtual ICollection<SEG_ROL_PERMISO> SEG_ROL_PERMISO { get; set; }
    }
}
