//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class SEG_ROL_PERMISO : Entity<long>
    {

        public int ID_ROL { get; set; }
        public int ID_PERMISO { get; set; }
    
        public virtual SEG_PERMISO SEG_PERMISO { get; set; }
        public virtual SEG_ROL SEG_ROL { get; set; }
    }
}
