//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class SEG_OPCION : Entity<int>
    {
        public SEG_OPCION()
        {
            this.SEG_ACCESO_USUARIO = new HashSet<SEG_ACCESO_USUARIO>();
        }

        public int ID_MODULO { get; set; }
        public int ID_PADRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string URL { get; set; }

        public virtual ICollection<SEG_ACCESO_USUARIO> SEG_ACCESO_USUARIO { get; set; }
        public virtual SEG_MODULO SEG_MODULO { get; set; }


    }
}
