//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CLIENTE
    {
        public decimal CODIGO_CLIENTE { get; set; }
        public string TIPO_IDENTIFICACION_1 { get; set; }
        public string NUMERO_IDENTIFICACION_1 { get; set; }
        public string TIPO_IDENTIFICACION_2 { get; set; }
        public string NUMERO_IDENTIFICACION_2 { get; set; }
        public decimal CODIGO_TIPO_CLIENTE { get; set; }
        public string TIPO_CLIENTE { get; set; }
        public Nullable<decimal> CODIGO_PAIS { get; set; }
        public string PAIS { get; set; }
        public string NACIONALIDAD { get; set; }
        public Nullable<decimal> CODIGO_SECTOR_ECONOMICO { get; set; }
        public string SECTOR_ECONOMICO { get; set; }
        public decimal CODIGO_ACTIVIDAD_ECONOMICA { get; set; }
        public string ACTIVIDAD_ECONOMICA { get; set; }
        public string CODIGO_CLASE_ACTIVIDAD_ECONOMICA { get; set; }
        public string CLASE_ACTIVIDAD_ECONOMICA { get; set; }
        public string CODIGO_SUB_ACTIVIDAD_ECONOMICA { get; set; }
        public string SUB_ACTIVIDAD_ECONOMICA { get; set; }
        public string TIPO_DE_PERSONA { get; set; }
        public string NOMBRES { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string APELLIDO_DE_CASADA { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_NACIMIENTO { get; set; }
        public string CODIGO_ESTADO_CIVIL { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public Nullable<decimal> TOTAL_INGRESOS { get; set; }
        public Nullable<decimal> CODIGO_PROFESION { get; set; }
        public string PROFESION { get; set; }
        public Nullable<decimal> CODIGO_OCUPACION { get; set; }
        public string OCUPACION { get; set; }
        public decimal CODIGO_EMPRESA { get; set; }
        public string CONOCIDO_COMO { get; set; }
        public string ALIAS { get; set; }
        public string DOMICILIO { get; set; }
        public int TOTAL_TRANSACCIONES { get; set; }
        public decimal TOTAL_MONTO { get; set; }
    }
}
