//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REPORTE_CONTROLPAGOS
    {
        public string CODIGO_CLIENTE { get; set; }
        public string NUMERO_PRODUCTO { get; set; }
        public string SECUENCIA { get; set; }
        public Nullable<double> VALOR_TRANSACCION { get; set; }
        public Nullable<System.DateTime> FECHA_APLICACION { get; set; }
        public Nullable<System.DateTime> FECHA_CALENDARIO { get; set; }
        public string FINANCIERA { get; set; }
        public string NUMERO_RECIBO { get; set; }
        public string ESTADO { get; set; }
        public string PERT_NOMBRE { get; set; }
        public string PERT_PRIMER_APELLIDO { get; set; }
        public string PERT_SEGUNDO_APELLIDO { get; set; }
        public string PERT_APELLIDO_CASADA { get; set; }
        public string PERT_DUI { get; set; }
        public string PERT_NIT { get; set; }
        public string PERT_NACIONALIDAD { get; set; }
        public Nullable<int> PERT_DEPARTAMENTO { get; set; }
        public Nullable<int> PERT_MUNICIPIO { get; set; }
        public string PERT_DOMICILIO { get; set; }
        public Nullable<System.DateTime> PERT_FECHA_NACIMIENTO { get; set; }
        public string PERT_LUGAR_NACIMIENTO { get; set; }
        public string PERT_ESTADO_CIVIL { get; set; }
        public string PERT_PROFESION { get; set; }
        public string TRAN_CODIGO_CAJERO { get; set; }
        public Nullable<int> TRAN_DEPARTAMENTO { get; set; }
        public Nullable<int> TRAN_MUNICIPIO { get; set; }
        public string TRAN_ORIGEN_FONDOS { get; set; }
        public Nullable<bool> INFO_DATOS_RECIBO { get; set; }
        public Nullable<bool> INFO_CALIDAD_IMPRESION { get; set; }
        public Nullable<bool> INFO_LLENO_DECLARACION { get; set; }
        public string INFO_MODALIDAD_PAGO { get; set; }
        public string INFO_VERSION_DECLARACION_JURADA { get; set; }
        public string INFO_QUIEN_LLENO_DECLARACION_JURADA { get; set; }
        public string INFO_DOCUMENTACION_REQUERIDA { get; set; }
        public string INFO_TELEFONO_CONTACTO { get; set; }
        public string INFO_SEGUIMIENTO { get; set; }
        public string CLIE_LUGAR_NACIMIENTO { get; set; }
        public Nullable<int> CLIE_DEPARTAMENTO { get; set; }
        public Nullable<int> CLIE_MUNICIPIO { get; set; }
        public string TRAN_AGENCIA_BANCARIA { get; set; }
        public string INFO_CONFIRMACION_UIF { get; set; }
        public Nullable<System.DateTime> INFO_FECHA_CONFIRMACION_UIF { get; set; }
        public Nullable<bool> INFO_COLECTOR { get; set; }
    }
}
