//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CREDITOS_ESCRITURADOS
    {
        public int Id_Fact { get; set; }
        public Nullable<decimal> CODIGO_CLIENTE { get; set; }
        public string ID_PRESTAMO { get; set; }
        public string AGENCIA { get; set; }
        public string SUCURSAL { get; set; }
        public string EJECUTIVO_VENTA { get; set; }
        public string VENDEDOR { get; set; }
        public Nullable<System.DateTime> FECHA_APERTURA { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public Nullable<int> PLAZO { get; set; }
        public string PRODUCTO_BANCO { get; set; }
        public string SUB_APLICACION { get; set; }
        public string LINEA_FINANCIERA { get; set; }
        public string PROGRAMA { get; set; }
        public string ORIGEN_RECURSOS { get; set; }
        public Nullable<double> MONTO_OTORGADO { get; set; }
        public Nullable<double> TASA_TOTAL { get; set; }
        public Nullable<double> PRESIO_VENTA { get; set; }
        public string SISTEMA { get; set; }
        public string PAIS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string UBICACION_FISICA { get; set; }
    }
}
