//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MUNICIPIO
    {
        public decimal CODIGO_PAIS { get; set; }
        public decimal CODIGO_DEPARTAMENTO { get; set; }
        public decimal CODIGO_MUNICIPIO { get; set; }
        public string NOMBRE { get; set; }
    }
}
