//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FINANCIERAS
    {
        public decimal TIPO_FINANCIERA { get; set; }
        public decimal CODIGO_FINANCIERA { get; set; }
        public string NOMBRE { get; set; }
    }
}
