//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TRANSACCIONES
    {
        //public string AGENCIA_BANCO;
        //public string CODIGO_CAJERO;

        public string CLASE_PRODUCTO { get; set; }
        public Nullable<decimal> CODIGO_CLIENTE { get; set; }
        public string NUMERO_PRODUCTO { get; set; }
        public string CODIGO_USUARIO { get; set; }
        public string SECUENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_APLICACION { get; set; }
        public string CODIGO_FINANCIERA { get; set; }
        public string COLECTOR_MOVIMIENTO { get; set; }
        public string TIPO_TRANSACCION { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_CALENDARIO { get; set; }
        public string CODIGO_AGENCIA_BANCO { get; set; }
        public Nullable<double> VALOR_TRANSACCION { get; set; }
        public string NUMERO_RECIBO { get; set; }
        public string CODIGO_PATRONO { get; set; }
        public string ESTADO_CARTERA { get; set; }
        public string COLECTOR_CONVENIO { get; set; }
        public string FACTURA_CONVENIO { get; set; }
        public Nullable<double> SALDO_CAPITAL { get; set; }
        public Nullable<double> SALDO_INTERES { get; set; }
        public Nullable<double> SALDO_SEGUROS_IVA { get; set; }
        public Nullable<double> SALDO_OTROS { get; set; }
        public Nullable<double> EXCEDENTE { get; set; }
        public Nullable<double> CAPITAL_VIGENTE { get; set; }
        public Nullable<double> CAPITAL_MORA { get; set; }
        public Nullable<double> CAPITAL_VENCIDO { get; set; }
        public Nullable<double> INTERES_VIGENTE { get; set; }
        public Nullable<double> INTERES_MORA { get; set; }
        public Nullable<double> INTERES_VENCIDO { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public Nullable<System.DateTime> FECHA_APERTURA { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<double> VALOR_CUOTA { get; set; }
        public Nullable<double> MONTO_OTORGADO { get; set; }
        public Nullable<decimal> VALOR_VALUO { get; set; }
        public Nullable<decimal> VALOR_CONTABLE { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public Nullable<decimal> TOTAL_INGRESOS { get; set; }
        public string CODIGO_AGENCIA { get; set; }
        public string ORIGEN_FONDOS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string AGENCIA_BANCO { get; set; }
        public string CODIGO_CAJERO { get; set; }
    }
}
