//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CLIENTE_TELEFONOS
    {
        public decimal CODIGO_CLIENTE { get; set; }
        public decimal SECUENCIA { get; set; }
        public string TIPO_TELEFONO { get; set; }
        public string AREA_TELEFONO { get; set; }
        public string NUM_TELEFONO { get; set; }
        public string EXTENCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string ACCESO_TELEFONO { get; set; }
        public string TELEFONO_PRINCIPAL { get; set; }
        public Nullable<decimal> CODIGO_DIRECCION { get; set; }
        public Nullable<decimal> CODIGO_TIPO_DIRECCION { get; set; }
    }
}
