//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SOLICITUDES_CREDITOS
    {
        public decimal CODIGO_DESTINO { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public decimal CODIGO_SUB_APLICACION { get; set; }
        public decimal NRO_SOLICITUD { get; set; }
        public decimal CODIGO_ESTADO_SOLICITUD { get; set; }
        public string CODIGO_APLICACION { get; set; }
        public string CODIGO_LINEA_CREDITO { get; set; }
        public decimal RESPONSABLE_SOLICITUD { get; set; }
        public decimal CODIGO_AGENCIA { get; set; }
        public string CODIGO_EJECUTIVO { get; set; }
        public decimal CUOTA_DEL_CREDITO { get; set; }
        public decimal VALOR_PRIMA_COMPLEMENTO { get; set; }
        public Nullable<decimal> NUMERO_PRESTAMO { get; set; }
        public Nullable<System.DateTime> FECHA_PROCESO { get; set; }
        public string PAIS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string UBICACION_FISICA { get; set; }
    }
}
