//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CLIENTE_DIRECCIONES
    {
        public decimal CODIGO_CLIENTE { get; set; }
        public decimal CODIGO_DIRECCION { get; set; }
        public string DIRECCION_PRINCIPAL { get; set; }
        public decimal CODIGO_PAIS { get; set; }
        public decimal CODIGO_DEPARTAMENTO { get; set; }
        public decimal CODIGO_MUNICIPIO { get; set; }
        public decimal CODIGO_SECTOR { get; set; }
        public string PAIS { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string URBANIZACION { get; set; }
    }
}
