//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REPORTE_VENTAS
    {
        public decimal CODIGO_CLIENTE { get; set; }
        public decimal CODIGO_ACTIVO { get; set; }
        public string CODIGO_USUARIO { get; set; }
        public decimal SECUENCIA_MOVIMIENTO { get; set; }
        public System.DateTime FECHA_VALIDA { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public decimal VALUO { get; set; }
        public decimal VALOR_CONTABLE { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public decimal CODIGO_AGENCIA { get; set; }
        public Nullable<decimal> TOTAL_INGRESOS { get; set; }
    }
}
