//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class PER_FACTOR : Entity<long>
    {
        public PER_FACTOR()
        {
            this.PER_CALIFICACION_FACTOR = new HashSet<PER_CALIFICACION_FACTOR>();
            this.PER_CONFIGURACION_FACTOR = new HashSet<PER_CONFIGURACION_FACTOR>();
            this.PER_HISTORIAL_PERFIL = new HashSet<PER_HISTORIAL_PERFIL>();
        }
    
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<PER_CALIFICACION_FACTOR> PER_CALIFICACION_FACTOR { get; set; }
        public virtual ICollection<PER_CONFIGURACION_FACTOR> PER_CONFIGURACION_FACTOR { get; set; }
        public virtual ICollection<PER_HISTORIAL_PERFIL> PER_HISTORIAL_PERFIL { get; set; }
    }
}
