//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class PER_COINCIDENCIA_LISTA: Entity<int>
    {
        public int ID_CLIENTE { get; set; }
        public int ID_LISTA { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime FECHA_ALERTA { get; set; }
        public string COINCIDENCIA { get; set; }
        public string SEGUIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public string USUARIO_ACTUALIZA { get; set; }
    }
}
