//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_CALIFICACION_FACTOR: Entity<long>
    {
        public long ID_FACTOR { get; set; }
        public string ID_ITEM { get; set; }
        public int PUNTAJE { get; set; }
    
        public virtual PER_FACTOR PER_FACTOR { get; set; }
    }
}
