//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_MATRIZ: Entity<long>
    {
        public MAT_MATRIZ()
        {
            this.MAT_MATRIZ_CONTROL_EVENTO = new HashSet<MAT_MATRIZ_CONTROL_EVENTO>();
            this.MAT_MATRIZ_CONTROL = new HashSet<MAT_MATRIZ_CONTROL>();
            this.MAT_MATRIZ_EVENTO_RIESGO = new HashSet<MAT_MATRIZ_EVENTO_RIESGO>();
        }

        public System.DateTime FECHA { get; set; }
        public string USUARIO { get; set; }

        public virtual ICollection<MAT_MATRIZ_CONTROL_EVENTO> MAT_MATRIZ_CONTROL_EVENTO { get; set; }
        public virtual ICollection<MAT_MATRIZ_CONTROL> MAT_MATRIZ_CONTROL { get; set; }
        public virtual ICollection<MAT_MATRIZ_EVENTO_RIESGO> MAT_MATRIZ_EVENTO_RIESGO { get; set; }
    }
}
