//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_CONTROL_EVENTO : Entity<long>
    {
        public long ID_CONTROL { get; set; }
        public long ID_EVENTO { get; set; }
    
        public virtual MAT_CONTROL MAT_CONTROL { get; set; }
        public virtual MAT_EVENTO_RIESGO MAT_EVENTO_RIESGO { get; set; }
    }
}
