//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MAT_CONTROL : Entity<long>
    {
        public MAT_CONTROL()
        {
            this.MAT_CONTROL_EVENTO = new HashSet<MAT_CONTROL_EVENTO>();
        }

        public int ID_AGENCIA { get; set; }
        public int ID_AUTOMATIZACION { get; set; }
        public int ID_DISENO { get; set; }
        public int ID_DOCUMENTACION { get; set; }
        public int ID_FRECUENCIA { get; set; }
        public int ID_MEZCLA { get; set; }
        public int ID_TIPO_CONTROL { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal TOTAL_POR { get; set; }
        public string OBSERVACIONES { get; set; }

        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
        public virtual MAT_CAT_AUTOMATIZACION MAT_CAT_AUTOMATIZACION { get; set; }
        public virtual MAT_CAT_DISENO MAT_CAT_DISENO { get; set; }
        public virtual MAT_CAT_DOCUMENTACION MAT_CAT_DOCUMENTACION { get; set; }
        public virtual MAT_CAT_FRECUENCIA MAT_CAT_FRECUENCIA { get; set; }
        public virtual MAT_CAT_MEZCLA MAT_CAT_MEZCLA { get; set; }
        public virtual MAT_CAT_TIPO_CONTROL MAT_CAT_TIPO_CONTROL { get; set; }
        public virtual ICollection<MAT_CONTROL_EVENTO> MAT_CONTROL_EVENTO { get; set; }
    }
}
