//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_MATRIZ_CONTROL: Entity<long>
    {
        public MAT_MATRIZ_CONTROL()
        {
            this.MAT_MATRIZ_CONTROL_EVENTO = new HashSet<MAT_MATRIZ_CONTROL_EVENTO>();
        }

        public int ID_AGENCIA { get; set; }
        public long ID_MATRIZ { get; set; }
        public long ID_CONTROL_ANTERIOR { get; set; }
        public string AUTOMATIZACION { get; set; }
        public string DISENO { get; set; }
        public string DOCUMENTACION { get; set; }
        public string FRECUENCIA { get; set; }
        public string MEZCLA { get; set; }
        public string TIPO_CONTROL { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal TOTAL_POR { get; set; }
        public string OBSERVACIONES { get; set; }

        public string ID_EVENTOS { get; set; }
        public string AGENCIA { get; set; }

        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
        public virtual MAT_MATRIZ MAT_MATRIZ { get; set; }
        public virtual ICollection<MAT_MATRIZ_CONTROL_EVENTO> MAT_MATRIZ_CONTROL_EVENTO { get; set; }
    }
}

