//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MAT_CAT_SEVERIDAD : Entity<int>
    {
        public MAT_CAT_SEVERIDAD()
        {
            this.MAT_EVENTO_RIESGO = new HashSet<MAT_EVENTO_RIESGO>();
            this.MAT_SEVERIDAD = new HashSet<MAT_SEVERIDAD>();
        }
    

        public string DESCRIPCION { get; set; }
        public decimal NIVEL { get; set; }
    
        public virtual ICollection<MAT_EVENTO_RIESGO> MAT_EVENTO_RIESGO { get; set; }
        public virtual ICollection<MAT_SEVERIDAD> MAT_SEVERIDAD { get; set; }
    }
}
