//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MAT_SEVERIDAD : Entity<int>
    {

        public int ID_SEVERIDAD { get; set; }
        public int ID_TIPO_RIESGO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual MAT_CAT_SEVERIDAD MAT_CAT_SEVERIDAD { get; set; }
        public virtual MAT_CAT_TIPO_RIESGO MAT_CAT_TIPO_RIESGO { get; set; }
    }
}
