//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MAT_CAT_TIPO_RIESGO : Entity<int>
    {
        public MAT_CAT_TIPO_RIESGO()
        {
            this.MAT_CAUSA_RIESGO = new HashSet<MAT_CAUSA_RIESGO>();
            this.MAT_RIESGO = new HashSet<MAT_RIESGO>();
            this.MAT_SEVERIDAD = new HashSet<MAT_SEVERIDAD>();
        }
    
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<MAT_CAUSA_RIESGO> MAT_CAUSA_RIESGO { get; set; }
        public virtual ICollection<MAT_RIESGO> MAT_RIESGO { get; set; }
        public virtual ICollection<MAT_SEVERIDAD> MAT_SEVERIDAD { get; set; }
    }
}
