//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_MATRIZ_EVENTO_RIESGO: Entity<long>
    {
        public MAT_MATRIZ_EVENTO_RIESGO()
        {
            this.MAT_MATRIZ_CONTROL_EVENTO = new HashSet<MAT_MATRIZ_CONTROL_EVENTO>();
        }

        public int ID_AGENCIA { get; set; }
        public long ID_MATRIZ { get; set; }
        public long ID_EVENTO_ANTERIOR { get; set; }
        public string UNIDAD { get; set; }
        public string FACTOR_RIESGO { get; set; }
        public string RIESGO { get; set; }
        public string CAUSA_RIESGO { get; set; }
        public string COMO { get; set; }
        public string DESCRIPCION { get; set; }
        public string PROBABILIDAD_OCURRENCIA { get; set; }
        public string IMPACTO { get; set; }
        public decimal RIESGO_INHERENTE { get; set; }
        public string COLOR_RIESGO_INHERENTE { get; set; }
        public decimal EFICACIA_CONTROL { get; set; }
        public string COLOR_RIESGO_RESIDUAL { get; set; }
        public decimal RIESGO_RESIDUAL { get; set; }

        public string AGENCIA { get; set; }

        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
        public virtual MAT_MATRIZ MAT_MATRIZ { get; set; }
        public virtual ICollection<MAT_MATRIZ_CONTROL_EVENTO> MAT_MATRIZ_CONTROL_EVENTO { get; set; }
        public string TRIMESTRE { get; set; }
        public int ANIO { get; set; }
    }
}
