//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_CAT_AGENCIA: Entity<int>
    {
        public MAT_CAT_AGENCIA()
        {
            this.ALE_ALERTA = new HashSet<ALE_ALERTA>();
            this.ALE_OPERACION_IRREGULAR = new HashSet<ALE_OPERACION_IRREGULAR>();
            this.MAT_CAT_UNIDAD = new HashSet<MAT_CAT_UNIDAD>();
            this.MAT_CONTROL = new HashSet<MAT_CONTROL>();
            this.MAT_EVENTO_RIESGO = new HashSet<MAT_EVENTO_RIESGO>();
            this.MAT_MATRIZ_CONTROL = new HashSet<MAT_MATRIZ_CONTROL>();
            this.MAT_MATRIZ_EVENTO_RIESGO = new HashSet<MAT_MATRIZ_EVENTO_RIESGO>();
        }


        public int CODIGO_AGENCIA { get; set; }
        public string NOMBRE { get; set; }


        public virtual ICollection<ALE_ALERTA> ALE_ALERTA { get; set; }
        public virtual ICollection<ALE_OPERACION_IRREGULAR> ALE_OPERACION_IRREGULAR { get; set; }
        public virtual ICollection<MAT_CAT_UNIDAD> MAT_CAT_UNIDAD { get; set; }
        public virtual ICollection<MAT_CONTROL> MAT_CONTROL { get; set; }
        public virtual ICollection<MAT_EVENTO_RIESGO> MAT_EVENTO_RIESGO { get; set; }
        public virtual ICollection<MAT_MATRIZ_CONTROL> MAT_MATRIZ_CONTROL { get; set; }
        public virtual ICollection<MAT_MATRIZ_EVENTO_RIESGO> MAT_MATRIZ_EVENTO_RIESGO { get; set; }
    }
}
