//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class MAT_EVENTO_RIESGO : Entity<long>
    {
        public MAT_EVENTO_RIESGO()
        {
            this.MAT_CONTROL_EVENTO = new HashSet<MAT_CONTROL_EVENTO>();
        }


        public int ID_AGENCIA { get; set; }
        public int ID_UNIDAD { get; set; }
        public int ID_FACTOR_RIESGO { get; set; }
        public long ID_RIESGO { get; set; }
        public long ID_CAUSA_RIESGO { get; set; }
        public string COMO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_PROBABILIDAD_OCURRENCIA { get; set; }
        public int ID_IMPACTO { get; set; }


        public virtual MAT_CAT_AGENCIA MAT_CAT_AGENCIA { get; set; }
        public virtual MAT_CAT_FACTOR_RIESGO MAT_CAT_FACTOR_RIESGO { get; set; }
        public virtual MAT_CAT_PROBABILIDAD_OCURRENCIA MAT_CAT_PROBABILIDAD_OCURRENCIA { get; set; }
        public virtual MAT_CAT_SEVERIDAD MAT_CAT_SEVERIDAD { get; set; }
        public virtual MAT_CAT_UNIDAD MAT_CAT_UNIDAD { get; set; }
        public virtual MAT_CAUSA_RIESGO MAT_CAUSA_RIESGO { get; set; }
        public virtual ICollection<MAT_CONTROL_EVENTO> MAT_CONTROL_EVENTO { get; set; }
        public virtual MAT_RIESGO MAT_RIESGO { get; set; }
    }
}
