//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_CAT_FACTOR_RIESGO: Entity<int>
    {
        public MAT_CAT_FACTOR_RIESGO()
        {
            this.MAT_EVENTO_RIESGO = new HashSet<MAT_EVENTO_RIESGO>();
        }
    
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<MAT_EVENTO_RIESGO> MAT_EVENTO_RIESGO { get; set; }
    }
}
